version: '3.8'

services:
  shopify:
    container_name: shopify_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - '/app/node_modules'
